### PR TITLE
Begin to document the API

### PR DESCRIPTION
**Pull request by yanick**
Also, I'm wondering. For the `list`, should it make sense to have the first parameter printed out as a title
if it's a non-empty string, rather than ignore it?

### CODE REVIEW

**Comment by 0x80** [comment]
@yanick I think there are things in the API we can improve, but so far I have copied everything 1-to-1 from Yarn as much as possible to not make this a "fork".

But I think at some point it might make sense to just improve focus on this library as a things by itself and not depend on Yarn anymore.

**Comment by 0x80** [comment]
@yanick Loved your reference to the bamischijf 😆

**Comment by 0x80** [comment]
@yanick I have decided to start diverging from the Yarn implementation for list. It is ugly and annoying to have this first parameter being completely useless. I didn't notice this before because I never used list myself. 

See #21

**Comment by yanick** [comment]
> I think there are things in the API we can improve, but so far I have copied everything 1-to-1 from Yarn as much as possible to not make this a "fork".
> But I think at some point it might make sense to just improve focus on this library as a things by itself and not depend on Yarn anymore.

That's a decision that is totally yours. Both goals -- to be a drop-in feature parity replacement for the Yarn library or to be inspired by the Yarn library but grow to be your own -- are equality valid. 

Of course, since I don't know how to leave good enough alone, I obviously am biased toward the latter, but that's just me. ;-)

**Comment by yanick** [comment]
> Loved your reference to the bamischijf 

Stole it from the examples, to be honest. But now I kind of have a hankering  for it. Hmm... I wonder if I could find some in our local Dutch store...

**Comment by yanick** [comment]
> I have decided to diverge from the Yarn implementation for list.

Woot! \o/

**Pull request merged**
